version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: gunicorn osu_course_search.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  django-q:
    build: .
    command: python manage.py qcluster
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - db
      - web
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  selenium:
    image: selenium/standalone-chrome:latest
    volumes:
      - /dev/shm:/dev/shm

volumes:
  postgres_data:
  static_volume: